### PR TITLE
Add search to demo

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done
Add search to demo

## QA
Run ‘gulp build’ then head to the demo and check the search box in as many viewports as you possibly can

## Details
Card: https://trello.com/c/kZ4WnBND

### CODE REVIEW

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kZ4WnBND&#x2F;48-add-search-to-ubuntu-theme-demo"> Add search to ubuntu theme demo</a>

**Comment by barrymcgee** [comment]
Is this overlay expected at 670px?

screenshot 2016-03-22 16 38 56

**Comment by grahambancroft** [comment]
@barrymcgee Ah, I forgot to add the $navigation-threshold variable, it’s set much lower in vanilla-framework. I’ve added it now.

**Comment by barrymcgee** [comment]
LGTM +1

**Pull request merged**
